# Generated by Django 4.2.5 on 2023-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_form_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
